### ISSUE TITLE
ur Project is good... thanks for sharing 

### ISSUE THREAD

**Issue by poornasandur** [Issam28/Brain-tumor-segmentation#1]
Hi Issam,
                   Thanks for sharing your project. Please help me in getting the ResUnet.hdf5 pre-trained file.

**Comment by Issam28** [comment]
i uploaded a pretrained model check it out

**Comment by poornasandur** [comment]
Hi, Thank you ...

**Comment by PoonamZ** [comment]
@poornasandur  Have u run with this code? Can u pls help me to remove the error below.
Thank you.

brain_seg = Training(batch_size=4,nb_epoch=3,load_model_resume_training=model_to_load)
Traceback (most recent call last):

  File "<ipython-input-9-251a74a62565>", line 1, in <module>
    brain_seg = Training(batch_size=4,nb_epoch=3,load_model_resume_training=model_to_load)

  File "/home/ujjwal/Brain-tumor-segmentation-master/train.py", line 39, in __init__
    self.model =load_model(load_model_resume_training,custom_objects={'gen_dice_loss': gen_dice_loss,'dice_whole_metric':dice_whole_metric,'dice_core_metric':dice_core_metric,'dice_en_metric':dice_en_metric})

  File "/home/ujjwal/anaconda2/lib/python2.7/site-packages/keras/models.py", line 238, in load_model
    raise ValueError('No model found in config file.')

ValueError: No model found in config file.
